#!/usr/bin/env bash

set -eo pipefail

if ! command -v cargo &>/dev/null; then
  echo "Error: cargo not found"
  exit 1
fi
echo "Building..."
cargo build --release --quiet || {
  echo "Error: cargo build failed"
  exit 1
}
echo "Copying"
SCRIPT_PATH="$(readlink -f "$0" | xargs -n1 dirname)"
mkdir -p "$SCRIPT_PATH/lua"
cp "$SCRIPT_PATH/target/release/libtoml_lua.so" "$SCRIPT_PATH/toml.so"
cargo clean --quiet
echo "Done!"
