#!/usr/bin/env bash

set -eo pipefail

if ! command -v cargo &>/dev/null; then
  echo "Error: cargo not found"
  exit 1
fi

echo "Building..."
cargo build --release --quiet || {
  echo "Error: cargo build failed"
  exit 1
}
echo "Copying"
ARTIFACT_NAME='libtoml_lua.so'
# script path
SCRIPT_PATH="$(readlink -f "$0" | xargs -n1 dirname)"

SOURCE="$SCRIPT_PATH/target/release/libtoml_lua.so"

mkdir -p "$SCRIPT_PATH/lua"
cp "$SOURCE" "$SCRIPT_PATH/lua/toml.so"

cargo clean --quiet
echo "Done!"
